name: assignment_sem6
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  bcrypt: ^1.1.3
  flutter:
    sdk: flutter
  go_router: ^15.1.3
  provider: ^6.1.5
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.15

flutter:
  uses-material-design: true
