name: assignment_sem6
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  bcrypt: ^1.1.3
  chewie: ^1.12.1
  file_picker: ^10.2.0
  flutter:
    sdk: flutter
  flutter_map: ^6.0.0
  flutter_map_marker_cluster: ^1.3.6
  go_router: ^15.1.3
  latlong2: ^0.9.1
  markdown_widget: ^2.3.2+8
  mutex: ^3.1.0
  path_provider: ^2.1.5
  provider: ^6.1.5
  share_plus: ^11.0.0
  uuid: ^4.5.1
  video_player: ^2.10.0
  video_player_macos: ^2.0.1
  video_player_win: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.15

flutter:
  uses-material-design: true
